# Generated by Django 4.1.7 on 2023-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('succeedingFee', models.IntegerField()),
            ],
        ),
    ]
